/* eslint-disable */

const TEST_DATA = [ { name: '123',
    status: 'GOOD SERVICE',
    text: '',
    Date: '',
    Time: '',
    _index: 1 },
  { name: '456',
    status: 'DELAYS',
    text: '\r\n                    <span class="TitleDelay">Delays</span>\r\n                    <span class="DateStyle">\r\n                    &nbsp;Posted:&nbsp;12/02/2016&nbsp; 6:04PM\r\n                    </span><br/><br/>\r\n                  <P>Due to track maintenance at <STRONG>Eastchester-Dyre Av,</STRONG> [5] trains are running with delays in both directions.</P>\r\n<P>Allow additional travel time.</P>\r\n                <br/><br/>\r\n              ',
    Date: '12/02/2016',
    Time: ' 6:04PM',
    _index: 1 },
  { name: '7',
    status: 'GOOD SERVICE',
    text: '',
    Date: '',
    Time: '',
    _index: 1 },
  { name: 'ACE',
    status: 'DELAYS',
    text: '\r\n                    <span class="TitleDelay">Delays</span>\r\n                    <span class="DateStyle">\r\n                    &nbsp;Posted:&nbsp;12/02/2016&nbsp; 6:03PM\r\n                    </span><br/><br/>\r\n                  <P>Due to signal problems at <STRONG>Rockaway Blvd</STRONG>, southbound [A] trains are running with delays. </P>\r\n<P>Allow additional travel time.</P>\r\n                <br/><br/>\r\n              ',
    Date: '12/02/2016',
    Time: ' 6:03PM',
    _index: 1 },
  { name: 'BDFM',
    status: 'GOOD SERVICE',
    text: '',
    Date: '',
    Time: '',
    _index: 1 },
  { name: 'G',
    status: 'GOOD SERVICE',
    text: '',
    Date: '',
    Time: '',
    _index: 1 },
  { name: 'JZ',
    status: 'GOOD SERVICE',
    text: '',
    Date: '',
    Time: '',
    _index: 1 },
  { name: 'L',
    status: 'GOOD SERVICE',
    text: '',
    Date: '',
    Time: '',
    _index: 1 },
  { name: 'NQR',
    status: 'GOOD SERVICE',
    text: '',
    Date: '',
    Time: '',
    _index: 1 },
  { name: 'S',
    status: 'GOOD SERVICE',
    text: '',
    Date: '',
    Time: '',
    _index: 1 },
  { name: 'SIR',
    status: 'GOOD SERVICE',
    text: '',
    Date: '',
    Time: '',
    _index: 1 } ];

module.exports = TEST_DATA;
