/* eslint-disable */

const TEST_DATA = [
 {
   "_index": 1,
   "hour": 15,
   "icon": "mostlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/mostlycloudy.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 80,
   "temp_metric": 27,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 0,
   "icon": "partlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
   "mday": 8,
   "mon": 7,
   "temp_english": 68,
   "temp_metric": 20,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 2,
   "icon": "clear",
   "icon_url": "http://icons.wxug.com/i/c/k/nt_clear.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 68,
   "temp_metric": 20,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 1,
   "icon": "partlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
   "mday": 8,
   "mon": 7,
   "temp_english": 66,
   "temp_metric": 19,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 4,
   "icon": "clear",
   "icon_url": "http://icons.wxug.com/i/c/k/nt_clear.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 65,
   "temp_metric": 18,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 0,
   "icon": "clear",
   "icon_url": "http://icons.wxug.com/i/c/k/nt_clear.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 71,
   "temp_metric": 22,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 9,
   "icon": "clear",
   "icon_url": "http://icons.wxug.com/i/c/k/clear.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 68,
   "temp_metric": 20,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 17,
   "icon": "chancetstorms",
   "icon_url": "http://icons.wxug.com/i/c/k/chancetstorms.gif",
   "mday": 6,
   "mon": 7,
   "temp_english": 86,
   "temp_metric": 30,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 6,
   "icon": "clear",
   "icon_url": "http://icons.wxug.com/i/c/k/clear.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 63,
   "temp_metric": 17,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 18,
   "icon": "chancetstorms",
   "icon_url": "http://icons.wxug.com/i/c/k/chancetstorms.gif",
   "mday": 6,
   "mon": 7,
   "temp_english": 84,
   "temp_metric": 29,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 23,
   "icon": "partlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 70,
   "temp_metric": 21,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 23,
   "icon": "clear",
   "icon_url": "http://icons.wxug.com/i/c/k/nt_clear.gif",
   "mday": 6,
   "mon": 7,
   "temp_english": 72,
   "temp_metric": 22,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 14,
   "icon": "partlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/partlycloudy.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 79,
   "temp_metric": 26,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 12,
   "icon": "clear",
   "icon_url": "http://icons.wxug.com/i/c/k/clear.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 75,
   "temp_metric": 24,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 21,
   "icon": "partlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/partlycloudy.gif",
   "mday": 6,
   "mon": 7,
   "temp_english": 75,
   "temp_metric": 24,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 19,
   "icon": "chancetstorms",
   "icon_url": "http://icons.wxug.com/i/c/k/chancetstorms.gif",
   "mday": 6,
   "mon": 7,
   "temp_english": 78,
   "temp_metric": 26,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 1,
   "icon": "clear",
   "icon_url": "http://icons.wxug.com/i/c/k/nt_clear.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 69,
   "temp_metric": 21,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 2,
   "icon": "partlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
   "mday": 8,
   "mon": 7,
   "temp_english": 65,
   "temp_metric": 18,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 18,
   "icon": "partlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/partlycloudy.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 79,
   "temp_metric": 26,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 16,
   "icon": "mostlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/mostlycloudy.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 80,
   "temp_metric": 27,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 11,
   "icon": "clear",
   "icon_url": "http://icons.wxug.com/i/c/k/clear.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 73,
   "temp_metric": 23,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 3,
   "icon": "partlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
   "mday": 8,
   "mon": 7,
   "temp_english": 64,
   "temp_metric": 18,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 20,
   "icon": "partlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/partlycloudy.gif",
   "mday": 6,
   "mon": 7,
   "temp_english": 77,
   "temp_metric": 25,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 13,
   "icon": "partlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/partlycloudy.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 77,
   "temp_metric": 25,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 22,
   "icon": "partlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 71,
   "temp_metric": 22,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 5,
   "icon": "clear",
   "icon_url": "http://icons.wxug.com/i/c/k/clear.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 63,
   "temp_metric": 17,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 17,
   "icon": "mostlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/mostlycloudy.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 80,
   "temp_metric": 27,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 22,
   "icon": "partlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
   "mday": 6,
   "mon": 7,
   "temp_english": 74,
   "temp_metric": 23,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 7,
   "icon": "clear",
   "icon_url": "http://icons.wxug.com/i/c/k/clear.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 64,
   "temp_metric": 18,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 10,
   "icon": "clear",
   "icon_url": "http://icons.wxug.com/i/c/k/clear.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 71,
   "temp_metric": 22,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 4,
   "icon": "partlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/nt_partlycloudy.gif",
   "mday": 8,
   "mon": 7,
   "temp_english": 64,
   "temp_metric": 18,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 19,
   "icon": "partlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/partlycloudy.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 77,
   "temp_metric": 25,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 20,
   "icon": "partlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/partlycloudy.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 75,
   "temp_metric": 24,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 3,
   "icon": "clear",
   "icon_url": "http://icons.wxug.com/i/c/k/nt_clear.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 67,
   "temp_metric": 19,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 8,
   "icon": "clear",
   "icon_url": "http://icons.wxug.com/i/c/k/clear.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 66,
   "temp_metric": 19,
   "year": 2017
 },
 {
   "_index": 1,
   "hour": 21,
   "icon": "partlycloudy",
   "icon_url": "http://icons.wxug.com/i/c/k/partlycloudy.gif",
   "mday": 7,
   "mon": 7,
   "temp_english": 73,
   "temp_metric": 23,
   "year": 2017
 }
];

module.exports = TEST_DATA;
