/* eslint-disable */

const TEST_DATA = [
      {
         "coord":{
            "lon":-64.75,
            "lat":32.33
         },
         "sys":{
            "type":1,
            "id":4169,
            "message":0.1755,
            "country":"BM",
            "sunrise":1484047259,
            "sunset":1484083967
         },
         "weather":[
            {
               "id":520,
               "main":"Rain",
               "description":"light intensity shower rain",
               "icon":"09d"
            }
         ],
         "main":{
            "temp":22,
            "pressure":1029,
            "humidity":72,
            "temp_min":16,
            "temp_max":16
         },
         "visibility":10000,
         "wind":{
            "speed":10.8,
            "deg":20
         },
         "clouds":{
            "all":75
         },
         "dt":1484081700,
         "id":3573345,
         "name":"Bermuda"
      },
      {
         "coord":{
            "lon":-73.97,
            "lat":40.78
         },
         "sys":{
            "type":1,
            "id":1972,
            "message":0.1882,
            "country":"US",
            "sunrise":1484050753,
            "sunset":1484084898
         },
         "weather":[
            {
               "id":804,
               "main":"Clouds",
               "description":"overcast clouds",
               "icon":"04d"
            }
         ],
         "main":{
            "temp":0.77,
            "pressure":1031,
            "temp_min":-2,
            "temp_max":2,
            "humidity":95
         },
         "visibility":16093,
         "wind":{
            "speed":1.5,
            "deg":110
         },
         "clouds":{
            "all":90
         },
         "dt":1484081100,
         "id":5125771,
         "name":"Manhattan"
      }
   ];

module.exports = TEST_DATA;
